# It will run `shards install` to install dependencies
language: crystal

# It will install Cake which will check code formatting,
# run specs, generate docs and build the release binary
script:
  - curl https://raw.githubusercontent.com/axvm/cake/master/install.sh | bash; source $HOME/.bashrc
  - cake travis
